#! /bin/bash
#

#sudo apt update
#
#echo .............Instalación de Wine.............
#sudo apt-get install wine
#
## Atril ya viene instalado en mate, solo hago un acceso directo
#cd /usr/share/applications/atril.desktop ~/Escritorio
#
#
#echo .............Instalación de Google Chrome.............
#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
#sudo dpkg -i chrome.deb
#rm chrome.deb
#cp /usr/share/applications/google-chrome.desktop ~/Escritorio
#
#
#echo .............Instalación de Anydesk.............
#wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
## wget https://download.anydesk.com/linux/anydesk_6.3.3-1_amd64.deb -O anydesk.deb
#sudo dpkg -i anydesk.deb
#rm anydesk.deb
#cd /usr/share/applications/anydesk.desktop ~/Escritorio




# Proxy
#export {HTTP,HTTPS,FTP}_PROXY="http://10.10.254.218:3128"
#export {http,https,ftp}_proxy="http://10.10.254.218:3128"

# Agregar la red
read -p "IP: " ip
nmcli device
read -p "Dispositivo: " dev
network_name='TEST09'
dns='10.1.4.111,10.1.4.112'
gateway='10.7.6.200'
nmcli connection add type ethernet ifname ${dev} con-name ${network_name} ip4 "${ip}/23" gw4 ${gateway} ipv4.dns ${dns}
