#! /bin/bash

# TODO Mover x11 a otra funcion
# TODO Mover accesos directos a otra funcion
# TODO Modificar la red "Red" si ya existe, sino crearla
# TODO ver configuracion del cups 

CREATE_USER_COMPLETED=false
INSTALL_PACKAGES_COMPLETED=false
NETWORK_CONFIGURED=false
PROXY_CONFIGURED=false
SAMBA_CONFIGURED=false
VNC_CONFIGURED=false
NETWORK_NAME='Red'
DNS='10.1.4.111,10.1.4.112'
GATEWAY='10.7.6.200'
PROXY="10.10.254.218"
PROXY_PORT="3128"
PROXY_IGNORED=("localhost" "127.0.0.0/8" "::1" "10.7.6.*" "10.7.7.*" "*.santafe.gob.ar" "*.santafe.gov.ar")
PACKAGES=(
	"x11vnc" # programa para control remoto de entornos linux
	"libreoffice" # suite de herramientas
	"ssh" # protocolo para control remoto de terminales
	"unrar" #para rars
	"unzip" # para zips
	"vlc" # reproductor de audio y videos
	"thunderbird" # correo
	"myspell-es" # correcion en castellano para libreoffice
	"ubuntu-restricted-extras" # algunas utilidades para ubuntu
	"firefox-locale-es" # traducción de firefox
	"ntp" # Protocolo para la sincronizacion del reloj
	"hplip hplip-gui" # drivers para impresoras HP
	"vim" # editor de texto
	"neovim" # fork de vim mejorado
	"gimp" # editor de imagenes
	"inkscape" # editor de imagenes vectorial
	"google-chrome-stable" # chrome
	"anydesk" # control remoto
	"wine" # interfaz para windows
	"ocsinventory-agent" # programa para gestión de inventario
	"cifs-utils" # utilidades para el protocolo cifs
	"net-tools" # utilidades de red
	"ethtool" # utilidad para controlar los drivers de red y hardware
	"putty" # cliente de terminal ssh/telnet integrada
)



function create_user(){
	clear
	echo "Configurar usuario"
	sudo useradd -m usuario
	sudo passwd usuario
	CREATE_USER_COMPLETED=true
}


function install_packages(){
	clear

	sudo apt update
	sudo apt upgrade
	sudo apt-get install "${PACKAGES[*]}"

	


	#echo .............Descativando Busqueda de Impresoras.............
	#sudo cp /home/administrador/Desktop/Instalacion\ Ubuntu/cups-browsed.conf /etc/cups/
	#echo .............Ignorar Error DESKTOP O ESCRITORIO.............
	#sudo cp /home/administrador/Escritorio/Instalacion\ Ubuntu/cups-browsed.conf /etc/cups/
	#sudo service cups-browsed restart
	#sudo service cups restart
	
	cp /usr/share/applications/{atril,vlc,thunderbird,gimp}.desktop ~/Escritorio
	cp /usr/share/applications/libreoffice-{calc,draw,impress,math,writer}.dekstop ~/Escritorio/

	sudo apt --fix-broken
	sudo apt upgrade
	INSTALL_PACKAGES_COMPLETED=false
}


function configure_proxy(){
	clear
	echo "Configurar proxy"
	gsettings set org.gnome.system.proxy.http host ${PROXY}
	gsettings set org.gnome.system.proxy.http port ${PROXY_PORT}
	gsettings set org.gnome.system.proxy.https host ${PROXY}
	gsettings set org.gnome.system.proxy.https port ${PROXY_PORT}
	gsettings set org.gnome.system.proxy.ftp host ${PROXY}
	gsettings set org.gnome.system.proxy.ftp port ${PROXY_PORT}

	no_proxy=""
	for str in "${PROXY_IGNORED[@]}"
	do
		no_proxy+="$str,"
	done
	gsettings set org.gnome.system.proxy ignore-hosts "${no_proxy}"
	echo "Proxy configurado"

	echo "Acquire::http::proxy \"http://10.7.6.6:3128\";
	Acquire::https::proxy \"http://10.7.6.6:3128\";
	Acquire::ftp::proxy \"http://10.7.6.6:3128\";" | sudo tee /etc/apt/apt.conf > /dev/null

	read -r
	PROXY_CONFIGURED=true
}


function configure_network() {
	clear
	echo "Configurar red"
	read -rp "IP: " ip
	nmcli device
	read -rp "Dispositivo: " dev
	if [[ -f "/etc/NetworkManager/system-connections/$NETWORK_NAME.nmconnection" ]]
	then
		nmcli connection delete "$NETWORK_NAME"
	fi
	nmcli connection add type ethernet ifname "$dev" con-name $NETWORK_NAME ip4 "$ip/23" gw4 "$GATEWAY" ipv4.dns "$DNS"
	nmcli connection up $NETWORK_NAME
	nmcli connection
	read -r
	NETWORK_CONFIGURED=true
}


function config_samba(){
	clear
	scan_dir=/home/usuario/scan
	share_dir=/home/usuario/compartida
	if [[ ! -d $scan_dir ]]
	then
		sudo mkdir $scan_dir
		sudo chown usuario:usuario $scan_dir
		sudo chmod 777 $scan_dir
		echo "[scan]
		path = /home/usuario/Escritorio/scan
		public = yes
		writable = yes
		browseable = yes
		read only = no
		force directory mode = 0777
		force create mode = 0777" | sudo tee -a /etc/samba/smb.conf > /dev/null
	fi

	if [[ ! -d $share_dir ]]
	then
		sudo mkdir $share_dir
		sudo chown usuario:usuario $share_dir
		sudo chmod 777 $share_dir
		echo "[compartida]
		path = /home/usuario/compartida
		public = yes
		writable = yes
		browseable = yes
		read only = no
		force directory mode = 0777
		force create mode = 0777" > /etc/samba/smb.conf
	fi

	sudo cp smb.conf /etc/samba/smb.conf
	sudo systemctl restart smbd
	read
	SAMBA_CONFIGURED=true
}


function config_vnc(){
	clear
	sudo cp x11vnc.service /etc/systemd/system/
	sudo systemctl enable x11vnc
	sudo systemctl start x11vnc
	systemctl status x11vnc
	read -r
	VNC_CONFIGURED=true
}


function print_mark(){
	printf " ("
	if $1
	then
		printf '\u2714'
	else
		printf '\u2A2F'
	fi
	printf ")\n"
}




while true
do
	clear
	echo "Instalador"
	printf "1. Crear usuario"
	print_mark $CREATE_USER_COMPLETED

	printf "2. Configurar red"
	print_mark $NETWORK_CONFIGURED

	printf "3. Configurar proxy"
	print_mark $PROXY_CONFIGURED

	printf "4. Instalar paquetes"
	print_mark $INSTALL_PACKAGES_COMPLETED

	printf "5. Configurar Samba"
	print_mark $SAMBA_CONFIGURED

	printf "6. Configurar X11VNC"
	print_mark $VNC_CONFIGURED

	echo "7. Salir"
	read -p "Opcion: " option

	case $option in
		1) create_user;;
		2) configure_network;;
		3) configure_proxy;;
		4) install_packages;;
		5) config_samba;;
		6) config_vnc;;
		7) break;;
	esac
done
