#! /bin/bash -x
PROXY_IGNORED=("localhost" "127.0.0.0/8" "::1" "10.7.6.*" "10.7.7.*" "*.santafe.gob.ar" "*.santafe.gov.ar")

no_proxy=""
for str in ${PROXY_IGNORED[*]}
do
	no_proxy+="$str,"
done
echo $no_proxy

