- name: Get inventory from repo
  hosts: localhost
  gather_facts: no
  tasks: 
    - name: download reports
      ansible.builtin.shell: ./download-reports.sh

    - name: parse data
      vars:
        networks: "{{ (lookup('file', 'networks.json') | from_json).data }}"
        users: "{{ (lookup('file', 'users.json') | from_json).data }}"
      ansible.builtin.copy:
        dest: inventory/inventory.yaml
        content: |
          all:
            children:
          {% for network in networks %}
              {{ network.name }}:
                hosts:
          {% for user in users if user.network_id == network.id %}
                  {{ user.ip }}: # {{ user.nombre }}
          {% endfor %}
          {% endfor %}
